name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: michaelb/github-profile-summary-cards@v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.CARDS }}
        with:
          USERNAME: ${{ github.repository_owner }}
